version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"
    groups:
      official-actions:
        patterns:
          - "actions/*"
      third-party-actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/doc"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docs"
