# ------------------------------------------------------------------------------
# Project: Hemerion Copyright (c) 2026, Onur Tuncer, PhD, Istanbul Technical University
#
# SPDX-License-Identifier: GPL-3.0-only License-Filename: LICENSE
# ------------------------------------------------------------------------------
# Script-mode (`cmake -P`) check that one packaged .fmu archive is actually loadable by an FMI importer. Registered as a
# ctest by hemerion_add_fmu_archive_test() (cmake/fmu_archive_test.cmake), one test per model per FMI version.
#
# What it defends. An .fmu is a zip whose *root* holds modelDescription.xml with binaries/ beside it; an importer that
# cannot find modelDescription.xml at the root rejects the archive outright. generateFMU() got this wrong once already
# -- `cmake -E tar` was handed absolute member names, so every member landed under a copy of the build machine's own
# path prefix and the root was empty (see cmake/generate_fmu.cmake's list of Hemerion-local changes). Nothing caught
# that but a human unzipping the file. This does.
#
# Deliberately not an FMI import: loading the FMU would need fmi4c and a running solver, which is examples/'s job. This
# is the packaging contract only, which is what the build step here is responsible for.
#
# Expects FMU_ARCHIVE, FMU_MODEL_IDENTIFIER and FMU_SCRATCH_DIR on the command line.
# ------------------------------------------------------------------------------

foreach(_required FMU_ARCHIVE FMU_MODEL_IDENTIFIER FMU_SCRATCH_DIR)
  if(NOT ${_required})
    message(FATAL_ERROR "verify_fmu_archive.cmake requires -D${_required}=<value>")
  endif()
endforeach()

if(NOT EXISTS "${FMU_ARCHIVE}")
  message(FATAL_ERROR "No archive at ${FMU_ARCHIVE} -- generateFMU()'s packaging step did not run or did not land here")
endif()

file(SIZE "${FMU_ARCHIVE}" _archive_bytes)
if(_archive_bytes EQUAL 0)
  message(FATAL_ERROR "${FMU_ARCHIVE} is empty")
endif()

# A stale extraction would let a since-deleted member keep the test green.
file(REMOVE_RECURSE "${FMU_SCRATCH_DIR}")
file(MAKE_DIRECTORY "${FMU_SCRATCH_DIR}")
file(
  ARCHIVE_EXTRACT
  INPUT
  "${FMU_ARCHIVE}"
  DESTINATION
  "${FMU_SCRATCH_DIR}")

if(NOT EXISTS "${FMU_SCRATCH_DIR}/modelDescription.xml")
  file(
    GLOB_RECURSE _found
    LIST_DIRECTORIES false
    RELATIVE "${FMU_SCRATCH_DIR}"
    "${FMU_SCRATCH_DIR}/*")
  message(FATAL_ERROR "${FMU_ARCHIVE} has no modelDescription.xml at its root -- an FMI importer rejects it.\n"
                      "Members found instead: ${_found}")
endif()

if(NOT IS_DIRECTORY "${FMU_SCRATCH_DIR}/binaries")
  message(FATAL_ERROR "${FMU_ARCHIVE} has no binaries/ directory at its root")
endif()

# The shared library itself, under binaries/<platform>/. Its stem is the modelIdentifier on every platform; only the
# prefix and suffix differ, so match on the stem rather than reconstructing the platform triple here.
file(GLOB_RECURSE _binaries LIST_DIRECTORIES false "${FMU_SCRATCH_DIR}/binaries/*")
set(_model_binary "")
foreach(_candidate IN LISTS _binaries)
  get_filename_component(_stem "${_candidate}" NAME_WE)
  if("${_stem}" STREQUAL "${FMU_MODEL_IDENTIFIER}" OR "${_stem}" STREQUAL "lib${FMU_MODEL_IDENTIFIER}")
    set(_model_binary "${_candidate}")
    break()
  endif()
endforeach()
if(NOT _model_binary)
  message(FATAL_ERROR "${FMU_ARCHIVE} carries no binary named ${FMU_MODEL_IDENTIFIER} under binaries/.\n"
                      "Found: ${_binaries}")
endif()

# modelDescription.xml is generated by loading the freshly built library and calling its write_description() export, so
# a description naming a *different* modelIdentifier means the archive was assembled from a stale staging directory --
# the archive would then load and instantiate the wrong model.
file(READ "${FMU_SCRATCH_DIR}/modelDescription.xml" _description)
if(NOT
   _description
   MATCHES
   "modelIdentifier=\"${FMU_MODEL_IDENTIFIER}\"")
  message(
    FATAL_ERROR "${FMU_ARCHIVE}'s modelDescription.xml does not declare modelIdentifier=\"${FMU_MODEL_IDENTIFIER}\"")
endif()

message(STATUS "${FMU_MODEL_IDENTIFIER}: archive layout OK (${_archive_bytes} bytes, ${_model_binary})")
